* Preface
Welcome to my doom configuration. I hope you find some good snippets to borrow from me.
* Color Theme
#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src
* Helpers
Doom provides a lot of helpers out of the box, but here are some of my own. Feel free to tell me if there are any viable alternative built into Doom or Emacs.
#+begin_src elisp
(defun get-string-from (filename)
  "Return the contents of FILENAME."
  (with-temp-buffer
    (insert-file-contents filename)
    (buffer-string)))
#+end_src
* MacOS exclusive configurations
#+begin_src elisp
(defun olav-open-safari ()
  (interactive)
  (shell-command "open -a Safari.app"))

(defun olav-open-discord ()
  (interactive)
  (shell-command "open -a Discord.app"))

(defun olav-open-riot ()
  (interactive)
  (shell-command "open -a Riot.app"))

(defun olav-open-chrome ()
  (interactive)
  (shell-command "open -a \"Google Chrome\".app"))

(defun olav-open-chrome ()
  (interactive)
  (shell-command "open -a \"Google Chrome\".app"))

(defun olav-open-visual-studio-code ()
  (interactive)
  (shell-command "open -a \"Visual Studio Code\".app"))

(defun olav-open-spotify ()
  (interactive)
  (shell-command "open -a Spotify.app"))

(defun olav-open-obs ()
  (interactive)
  (shell-command "open -a OBS.app"))

(defun olav-open-finder ()
  (interactive)
  (shell-command "open -a Finder.app"))

(when IS-MAC (setq mac-option-key-is-meta t)
      (setq mac-right-option-modifier nil)
      (setq frame-resize-pixelwise t)
      (map! :leader (:prefix ("e" . "open external") :desc "Visual Studio Code" "v" 'olav-open-visual-studio-code))
      (map! :leader (:prefix ("e" . "open external") :desc "Safari" "s" 'olav-open-safari))
      (map! :leader (:prefix ("e" . "open external") :desc "Chrome" "c" 'olav-open-chrome))
      (map! :leader (:prefix ("e" . "open external") :desc "Discord" "d" 'olav-open-discord))
      (map! :leader (:prefix ("e" . "open external") :desc "Riot" "r" 'olav-open-riot))
      (map! :leader (:prefix ("e" . "open external") :desc "Spotify" "p" 'olav-open-spotify))
      (map! :leader (:prefix ("e" . "open external") :desc "OBS" "o" 'olav-open-obs))
      (map! :leader (:prefix ("e" . "open external") :desc "Finder" "f" 'olav-open-finder))
      )
#+end_src
* Personal Information
#+begin_src elisp
(setq user-full-name "Olav Fosse"
      user-mail-address "fosseolav@gmail.com")
#+end_src
* Emacs Radio
This is a radio program I've written. I'm planning to package and publish it to Melpa some time. For now it lives in my configuration.
#+begin_src elisp
; should be defvar when packaged
(setq er-channels '(("def con | soma fm" . "http://somafm.com/defcon256.pls")
                    ("cyberia | lainon". "http://lainon.life:8000/cyberia.ogg")
                    ("cafe | lainon" . "http://lainon.life:8000/cafe.ogg")
                    ("swing | lainon" . "http://lainon.life:8000/swing.ogg")
                    ("everything | lainon" . "http://lainon.life:8000/everything.ogg")
                    ("metal | soma fm" . "http://somafm.com/metal130.pls")
                    ("groove salad | soma fm" . "http://somafm.com/groovesalad256.pls")
                    ("secret agent | soma fm" . "http://www.somafm.com/secretagent.pls")
                    ("ryno the bearded" . "http://stream.ryno.cc/oo")
                    ("jamendo lounge" . "http://streaming.radionomy.com/JamendoLounge") ; Great music, but the songs repeat themselfs frequently
                    ))

(defun er-alist-keys (alist) (mapcar 'car alist))

(defun er-stop () (interactive) (when (boundp 'radio-process) (delete-process radio-process)))

(defun er-play-low-level (url) (setq radio-process (start-process "emacs-radio" nil "vlc" "--no-video" "-I" "rc" url)))

(defun er-get-url ()
  (setq er-channel (completing-read
                       "Channel: "
                       (er-alist-keys er-channels)
                       nil nil))
  (or (cdr (assoc er-channel er-channels)) er-channel))

(defun er-play ()
  (interactive)
  (setq url (er-get-url))
  (er-stop)
  (er-play-low-level url))

(map! :leader (:prefix ("r" . "radio") :desc "Play radio" "p" 'er-play))
(map! :leader (:prefix ("r" . "radio") :desc "Stop radio" "s" 'er-stop))
#+end_src
* Projectile
I like how doom handles projects out of the box
#+begin_src elisp
(setq projectile-project-search-path '("~/code/"))
#+end_src
Unfortunately adding ~/.doom.d, ~/org and ~/roam to the search path did not work as expected. Therefore I have to add them manually.
* Org
** Better defaults
This makes it possible to use <s to insert a code block
#+begin_src elisp
(require 'org-tempo)
#+end_src
** Non-linear notetaking
The primary purpose of note-taking should not be for storing ideas, but for developing them. When we take notes, we should ask: “In what context do I want to see this note again?" - somebody

I use org-roam to take notes in a graph(network). The way it works is that whenever you link to a note from another note an edge(connection) is created between the two. org-roam provides easy between nodes through their edges. This is useful because it allows me to build useful connections between my notes regardless of which topic(s) they belong to. I was inspired by the zettelkasten method although I don't strictly follow it.
#+begin_src elisp
(setq org-roam-directory "~/roam")
(setq org-roam-index-file "index.org")
#+end_src
[[file:roam_illustration.svg][An org-roam graph]]
** Linear notetakin
I also use org-mode for organizing knowledge that is more linear in nature. Among other things I manage todos, project ideas, quotes, reading lists, song lists, my calendar, gift ideas, wishlist and youtube scripts all in org-mode.

In addition to that i track my habits in org using org-habits.
#+begin_src elisp
(require 'org-habit)
#+end_src
* Competitive programming
I do competitive programming in cpp and for that I rely heavily on my snippets. All of them are hand written by me and only intended for my specific competitive programming workflow.
#+begin_src elisp
(set-file-template! 'c++-mode :trigger "template")
(setq yas--default-user-snippets-dir "~/.doom.d/snippets")
#+end_src

I use c++11 for all my competitive programming and that is all I use cpp for so always using c++11 linting is sufficient for me.
#+begin_src elisp
(add-hook 'c++-mode-hook (lambda () (setq flycheck-gcc-language-standard "c++11")))
(add-hook 'c++-mode-hook (lambda () (setq flycheck-clang-language-standard "c++11")))
#+end_src

I also use these functions for quickly compiling, running and testing cpp programs.
#+begin_src elisp
(defun comp-open-buffer (buffer &optional switch-window)
      (setq temp kill-buffer-query-functions)
      (setq kill-buffer-query-functions nil)
      (+popup/close-all)
      (+popup-buffer buffer)
      (setq kill-buffer-query-functions temp)
      (when switch-window (switch-to-buffer-other-window buffer))
      )

(defun comp-compile () (interactive)
       (setq temp compilation-read-command)
       (setq compilation-read-command nil)
       (comp-open-buffer (compile (concat "g++ \"" buffer-file-name "\" --std=c++11 -o /tmp/comp-a.out")))
       (setq compilation-read-command temp)
       )

(defun comp-run () (interactive)
       (comp-open-buffer (make-comint "comp-run" "/tmp/comp-a.out")) t)

(defun comp-test () (interactive)
       (setq buffer (current-buffer))
       (comp-open-buffer (make-comint "comp-test" "/tmp/comp-a.out") t)
       (setq y (clipboard-yank))
       (insert (if (eq y nil) "" y)
               (comint-send-input nil nil))
       (other-window)
       )

(map! :leader (:prefix ("k" . "competitive") :desc "Comp compile" "c" 'comp-compile))
(map! :leader (:prefix ("k" . "competitive") :desc "Comp run" "r" 'comp-run))
(map! :leader (:prefix ("k" . "competitive") :desc "Comp test" "t" 'comp-test))
#+end_src
* IRC
At the moment I only use circe for trigex's irc server. For freenode I use Matrix. I will probably move to using circe sooner or later once I get bouncing set up for that.
Inlining images plus 1000 line znc history lead to unbearable loading times. Therefore these are commented out.

I figured image in-lining is a bit... Dangerous.
#+begin_src elisp
;(require 'circe-display-images)
;(enable-circe-display-images)
#+end_src

#+begin_src elisp
(map! :leader (:prefix ("o" . "+open") :desc "Open circe" "i" '=irc))
(after! circe
  (set-irc-server! "trigex.moe-znc"
                   `(:host "znc.trigex.moe"
                     :port 5597
                     :user "fossegrim/trigex"
                     :nick "fossegrim"
                     :realname "fossegrim"
                     :pass (lambda (&rest _) (get-string-from "~/.znc")) ; relax it's randomly generated, not used anywhere else and my disk is encrypted
                     :channels ("#clan" "#img-dump" "#sethhateclub" "#bunker"))))

(when nil (set-irc-server! "chat.freenode.net"
                   `(:tls t
                     :port 6697
                     :nick "fossegrim"
                     :sasl-username "fossegrim"
                     :sasl-password (lambda (&rest _) (get-string-from "~/.freenode")) ; relax it's randomly generated, not used anywhere else and my disk is encrypted
                     :channels ("#emacs" "#haskell" "##c++"))))
#+end_src

* Web Browsing
I use xwidget-webkit which is a way of embedding a webkit browser inside of Emacs. I use xwidget-webkit whenever I am to open a webpage from within Emacs. For example if I am opening an link from my RSS feed or IRC which do inside of Emacs.
#+begin_src elisp
(defun olav-is-xwidget-webkit-buffer-p (buffer) (string-prefix-p "*xwidget webkit: " (buffer-name buffer)))

(defun olav-xwidget-webkit-buffer ()
  "xwidget-webkit buffer or nil if doesn't exist"
  (seq-find #'olav-is-xwidget-webkit-buffer-p (buffer-list)))

(defun olav-browse (&optional url second-argument)
  (interactive)
  (persp-switch "*BROWSER*")
  (if (called-interactively-p)
      (when (not (olav-xwidget-webkit-buffer)) (xwidget-webkit-browse-url "https://fossegr.im" nil))
    (xwidget-webkit-browse-url url nil))
    (switch-to-buffer (olav-xwidget-webkit-buffer)))
(setq browse-url-browser-function 'olav-browse)
(map! :leader (:prefix ("o" . "open") :desc "Open browser" "b"  'olav-browse))
#+end_src
* RSS
#+begin_src elisp
(setq elfeed-feeds
      '("http://fossegr.im/feed.xml"
        "https://www.youtube.com/feeds/videos.xml?channel_id=UCWQ1f0ZhD-qhJB3AfJEoW0w" ; My channel ? (haven't checked)
        "https://protesilaos.com/codelog.xml"
        "https://www.distrotube.com/phpbb/app.php/feed"
        ;"https://www.kode24.no/?lab_viewport=rss"
        "https://xkcd.com/atom.xml"
        ;"https://news.ycombinator.com/rss"
        ;"https://www.reddit.com/r/emacs/new.rss"
        "https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" ; Luke Smith
        "https://www.kode24.no/?lab_viewport=rss"
        ))
(defun olav-rss ()
  (interactive)
  (elfeed-update)
  (persp-switch "*RSS*")
  (=rss))
(map! :leader (:prefix ("o" . "open") :desc "Open elfeed" "l"  'olav-rss))
#+end_src

* Torrent
Yes.

Emacs has some torrent clients, but I couldn't get any of them to work very well.

#+begin_src elisp
;(defun olav-mentor ()
;  (interactive)
;  (persp-switch "*TORRENT*")
;  (mentor))
;(map! :leader (:prefix ("o" . "open") :desc "Open mentor" "m" 'olav-mentor))
;(setq mentor-rtorrent-download-directory "~/Downloads")
;(after! 'mentor
;  (define-key mentor-files-mode-map "j" 'mentor-decrease-priority)
;  (define-key mentor-files-mode-map "k" 'mentor-increase-priority))
#+end_src

#+begin_src elisp
;(defun olav-torrent ()
;  (interactive)
;  (persp-switch "*TORRENT*")
;  (transmission)
;  )
;(evil-set-initial-state 'transmission-mode 'normal)
;(add-hook 'transmission-mode 'disable-evil-mode)
;(map! :leader (:prefix ("o" . "open") :desc "Open torrent" "m" 'olav-torrent))

;(after! transmission
;  (defun olav-add-magnet (magnet)
;    (interactive "sMagnet: ")
;    (transmission-add magnet))
;  (define-key transmission-mode-map "a" 'olav-add-magnet)
  ;)
#+end_src

* Media Viewers
Since I am inside Emacs all the time either way it makes sense to use it to open media files such as books and videos. I find Preview.app to work better than the Emacs pdf viewers so that is what I use to read books. Ideally I would want to open the media inside of xwidget-webkit, but I have not found a way to do this so far.
#+begin_src elisp
(defun olav-open-book ()
  (interactive)
  (setq temp default-directory)
  (cd "~/Google Drive/Books")
  (call-interactively 'counsel-find-file-extern)
;  (counsel-find-file-extern (+default/find-file-under-here))
  (setq default-directory temp)
)

(defun olav-open-anime ()
  (interactive)
  (setq temp default-directory)
  (cd "~/anime")
  (call-interactively 'counsel-find-file-extern)
  ;(counsel-find-file-extern (+default/find-file-under-here)
  (setq default-directory temp)
)

(map! :leader (:prefix ("o" . "open") :desc "Open a book" "B" 'olav-open-book))
(map! :leader (:prefix ("o" . "open") :desc "Open an anime episode" "A" 'olav-open-anime))
#+end_src
* Scratch Perspective
I use a scratch perspective to do tasks that don't fit in the current perspective or any other project. For instance if I am to install a global package when I am in the irc perspective I would switch to the scratch perspective an do it there. This serves as an alternative to pulling up an external terminal.
#+begin_src elisp
(defun olav-scratch ()
  (interactive)
  (if (+workspace-exists-p "*SCRATCH*")
      (persp-switch "*SCRATCH*")
      (progn (persp-switch "*SCRATCH*")
             (switch-to-buffer "*scratch*")))
)

(map! :leader (:prefix ("o" . "open") :desc "Open scratch" "s" 'olav-scratch))
#+end_src

* Other
I don't like, or understand for that matter the default behavior of `SPC w m m`. Therefore I rebound it to delete-other-windows which just works.
#+begin_src elisp
(map! :leader (:prefix ("w" . "window") (:prefix ("m" . "maximize") :desc "Actually maximize (as opposed to the default behaviour)" "m" 'delete-other-windows)))
#+end_src
I like relative line numbers
#+begin_src elisp
(setq doom-line-numbers-style 'relative)
#+end_src
